name: Application Lint

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_linter:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Build & Run Lint
        run: |
          npm ci
          npm run build
          npm run lint
